### ISSUE TITLE
Move new edits from README.rtf to README.md

### ISSUE THREAD

**Issue by mpinsky** [pinskylab/project_velocity#4]
Jim has made some new edits to the .rtf readme. Would be good to get those over to the .md file.

**Comment by mstuart1** [comment]
Hi Jim,

The .md file is not R-markdown, its just a simple text file.  I had already converted your README to the simple markdown, and I’ll add in any changes I notice, but if I miss anything, just click on the pencil in the Github webpage and fix it like you would in any text editor.

Thanks!
Michelle

On Aug 27, 2019, at 8:25 AM, JWMorley <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll leave this to Michelle, I haven't learned R-markdown yet. There are some notes on the README, at the bottom, that describe old files I took off because they weren't used in the final version. I suppose Malin has this code stored elsewhere. Probably can delete those descriptions.
